### ISSUE TITLE
Add scraped data to data frame.

### ISSUE THREAD

**Issue by AmritPatel** [MattThomas9/Home-Buyer-Fire#1]
1. import pandas.
2. Add all `SoldHome` variables to a `pandas` data frame for easier post processing.

**Comment by MattThomas9** [comment]
Completed! See Commit: https://github.com/MattThomas9/Home-Buyer-Fire/commit/6e78218914d08b26dd87b23b87d1ab0a674a0f6a
@AmritPatel
